### ISSUE TITLE
Determine how to handle before_request for gRPC

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#113]
I discovered that I did something totally wrong when I implemented our grpc transport.

All of our HTTP transports call `credentials.before_request` to get the authorization header populated ([here](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/8e1dc4f0345bbcfbe0f43ce40a5f9152b56db652/google/auth/transport/requests.py#L167)). However, the gRPC transport instead calls `credentials.refresh` directly and constructs the header itself ([here](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/8e1dc4f0345bbcfbe0f43ce40a5f9152b56db652/google/auth/transport/grpc.py#L50)).

I think the gRPC transport needs to do the same as the others, but that's where it gets tricky. `before_request` takes 4 arguments `request, method, url, request_headers`. gRPC provides our auth plugin with a context that looks like `AuthMetadataContext(service_url='https://pubsub.googleapis.com/google.pubsub.v1.Publisher', method_name='ListTopics')`. Does it make sense to call `before_request(http_request, context.method_name, context.service_url, headers)` even though `context.method_name` is not an HTTP method? It it okay to overload the term `method` for different transports?

@dhermes @lukesneeringer thoughts?

**Comment by dhermes** [comment]
I never understood why we cared that there was a gRPC "transport" since it can't do much/any of the handshakes over the wire. So in that light, why do we care about giving it a novel interface?

**Comment by jonparrott** [comment]
@dhermes I'm not sure what you mean. What's the alternative?

**Comment by dhermes** [comment]
Just a module with gRPC helpers (which is essentially what it is already).

**Comment by jonparrott** [comment]
What would you remove from the current module? Or do you just not like that it's in `google.auth.transports`. 

At any rate, gRPC needs to support all of our existing credentials and needs to interact with them properly, so the gRPC auth metadata plugin needs to call `before_request` just like everything else.

**Comment by jonparrott** [comment]
This might be easier to explain in code https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/116

The key thing I'm stuck on here is look at the updated docstring for `before_request`.
