### ISSUE TITLE
Determine how to deal with multiple audiences for jwt.Credentials

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#114]
JWT bearer credentials require an audience that matches the service URL to work.

Right now, JWT credentials don't require an audience when constructing, but instead can [generate a one-time token](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/8e1dc4f0345bbcfbe0f43ce40a5f9152b56db652/google/auth/jwt.py#L499) during `before_request`. This works, but unfortunately this is pretty awful performance-wise.

My best as to why we did this is because within one client we may actually be talking to two different audiences. Consider pubusb - there is the publisher audience (`https://pubsub.googleapis.com/google.pubsub.v1.Publisher`) and the subscriber audience (`https://pubsub.googleapis.com/google.pubsub.v1.Subscriber`).

I see two options for making this better:

1. Store a cache of tokens for every given audience. This has lots of problems.
2. Make our clients pass in `credentials.with_claims(audience='...')` (example [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/c79fc926092a4953b1c9938ebc8ae74e4fc629b9/pubsub/google/cloud/pubsub/client.py#L102)) instead of just credentials. This means that we'll essentially be using a copy of the credentials for each audience (pubsub will have two), so they will likely refresh at different times (which I don't consider a problem).

@dhermes @lukesneeringer thoughts?

**Comment by dhermes** [comment]
1. I don't understand the "pretty awful performance-wise" piece you are referring to
1. I don't see much wrong with asking the caller to be aware of the audience. Libraries like `google-cloud-python` can handle this without being a burden on users.

**Comment by jonparrott** [comment]
> I don't understand the "pretty awful performance-wise" piece you are referring to

Generating a new JWT for every request adds a lot of overhead. It's much better to only generate that once.

> I don't see much wrong with asking the caller to be aware of the audience.

Great, I'll do what I described in (2) above. I'll remove the per-request one-time JWT logic. We can always add that back as a new credential type later if needed, but if we hit 1.0 with that behavior we're married to it.
