### ISSUE TITLE
Make oauth2.Credentials attributes public

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#121]
To facilitate serialization, `token`, `refresh_token`, `token_uri`, `client_id`, and `client_secret` should all be publicly readable.

```python
attrs = {
    'access_token': credentials.token,
    'refresh_token': credentials.refresh_token,
    'token_uri': credentials.token_uri,
    'client_id': credentials.client_id,
    'client_secret': credentials.client_secret,
}
```

**Comment by dhermes** [comment]
Why is this required to "facilitate serialization"?

**Comment by jonparrott** [comment]
@dhermes because we don't plan to provide any support for storage in 1.0.0. However, users might want to implement it themselves. They shouldn't have to get at private attrs to do so.

Also, in the event we do implement storage, I'd prefer if storage didn't have "privileged" access to credential members.

**Comment by dhermes** [comment]
Ah gotcha. Makes sense

**Comment by jonparrott** [comment]
Resolved by https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/124
