### ISSUE TITLE
Decide how to deal with covering import guards

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#127]
Context: https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/125

**Comment by jonparrott** [comment]
Since removing the optional dependencies, this is less of a concern. Closing.

**Comment by dhermes** [comment]
@jonparrott Why so many `ImportError` left to catch?

```
$ git grep 'except ImportError'
additional_packages/google_auth_oauthlib/google_auth_oauthlib/helpers.py:except ImportError:  # pragma: NO COVER
google/__init__.py:except ImportError:
google/auth/_oauth2client.py:except ImportError:
google/auth/_oauth2client.py:except ImportError:
google/auth/app_engine.py:except ImportError:
google/auth/transport/grpc.py:except ImportError:  # pragma: NO COVER
google/auth/transport/requests.py:except ImportError:  # pragma: NO COVER
google/auth/transport/urllib3.py:except ImportError:  # pragma: NO COVER
google/auth/transport/urllib3.py:except ImportError:  # pragma: NO COVER
tests/transport/test_grpc.py:except ImportError:  # pragma: NO COVER
$ # WHEN
$ git log -1 --pretty=%H
1049bb25448696b0958e665eacd13bbd297a42f5
```

**Comment by jonparrott** [comment]
> additional_packages/google_auth_oauthlib/google_auth_oauthlib/helpers.py:except ImportError:  # pragma: NO COVER

Will fix.

> google/__init__.py:except ImportError:

Part of the namespace package stuff.

> google/auth/_oauth2client.py:except ImportError:

Covered

> google/auth/app_engine.py:except ImportError:

Covered

> google/auth/transport/*.py:except ImportError:  # pragma: NO COVER

Transports are *all* optional, and must be explicitly installed. I do not see this as a problem. I may be able to be convinced otherwise.

> tests/transport/test_grpc.py:except ImportError:  # pragma: NO COVER

This is needed so PyPy doesn't 'splode.
