### ISSUE TITLE
Consider splitting oauthlib integration into separate package

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#133]
So, as I look towards 1.0.0, I'm considering splitting the oauthlib integration sections into a separate package.

Advantages:
1. This library can go 1.0.0 without worrying about potentially breaking changes in the oauthlib integrations.
2. We can remove the "extra" in setup.py.
3. This library remains a smaller, focused core.
4. The separate package can iterate quickly on top of the 1.0.0 interface of this package.
5. We can keep the separate package in this repository like we did with google_auth_httplib2.

Disadvantages:
1. Another package means more overhead in terms of distribution and documentation.
2. Less pretty import path.

I've mostly talked myself into doing this, but do you have any reservations or thoughts @dhermes @lukesneeringer?

**Comment by dhermes** [comment]
I like it!
