### ISSUE TITLE
Add a five minute buffer to all expiration checks

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#141]

**Comment by dhermes** [comment]
Isn't this already built in? From the [`oauth2client` codebase][1]:

```python
CLOCK_SKEW_SECS = 300  # 5 minutes in seconds
```

[1]: https://github.com/google/oauth2client/blob/c055e7f7f5b7f7f9fe8ba12bbf7e297fccc2b59b/oauth2client/crypt.py#L29

**Comment by jonparrott** [comment]
I left it out when I wrote this library. :)

**Comment by dhermes** [comment]
But that's built into the spec, i.e. it wasn't just a quirk of `oauth2client`.

**Comment by jonparrott** [comment]
Which spec? I don't remember reading about that. I might have overlooked it.

There's also an internal debating on-going about what the interval should be. :)

**Comment by dhermes** [comment]
Not sure which spec? Tried googling just now and gave up.

**Comment by jonparrott** [comment]
*insert shruggie*

**Comment by dhermes** [comment]
The [JWT profile / ID token spec][2] and the [JWT spec][1] mention "skew" but they don't give specific values. For example:

>  The JWT MUST contain an "exp" (expiration time) claim that limits the time window during which the JWT can be used.  The authorization server MUST reject any JWT with an expiration time that has passed, subject to allowable clock skew between systems.  Note that the authorization server may reject JWTs with an "exp" claim value that is unreasonably far in the future.

[1]: https://tools.ietf.org/html/rfc7519
[2]: https://tools.ietf.org/html/rfc7523
