### ISSUE TITLE
Add CLI tool to generate 3LO credentials

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/google-auth-library-python#152]
I hacked together the following helper around the new `flow` feature to generate credentials for various python samples:
https://gist.github.com/proppy/b1e0719f13e3f477a2e0999d72e6cde5

Do you think that would be useful as part of this repo and distributed thru pip?

That way samples could easily point to the tool in their README, instead of cluttering the code with a custom authorization logic.

**Comment by jonparrott** [comment]
@vchudnov-g I think this overlaps well with the work you're doing. Thoughts?

**Comment by vchudnov-g** [comment]
This does overlap quite a bit. I suggest we hold off on submitting this for two reasons:

* there's a [similar  standalone tool](https://github.com/google/oauth2l/blob/master/go/oauth2util/main/main.go) out already (admittedly, in Go) and I'd like to reduce the proliferation of tools around auth

* this is functionality that I'm trying to design sensibly and coherently across languages. Contact me internally for details.

**Comment by jonparrott** [comment]
The oauthlib integration for this library is now a separate package (https://github.com/GoogleCloudPlatform/google-auth-library-python-oauthlib). I'm happy to coordinate iterating this helper over there where there's less pressure to go 1.0.0.

**Comment by proppy** [comment]
This now part of google-auth-oauthlib.
