### ISSUE TITLE
Requests support on App Engine

### ISSUE THREAD

**Issue by yuri-wisestamp** [GoogleCloudPlatform/google-auth-library-python#163]
I see that you're relying directly on Requests which is known not to be recommended when working on App Engine. How are we supposed to address this issue?

**Comment by jonparrott** [comment]
Requests works on standard with just a little work: https://cloud.google.com/appengine/docs/standard/python/issue-requests (see the Requests tab).

This library also supports urrlib3 and there's a separate library that supports httplib2: https://pypi.python.org/pypi/google-auth-httplib2
