### ISSUE TITLE
"authorized_user" credential has no project_id

### ISSUE THREAD

**Issue by achampion** [GoogleCloudPlatform/google-auth-library-python#164]
Wasn't sure whether to raise the issue here or in `google-cloud-python`.  

    google-auth: 1.0.1
    google-cloud-core: 0.24.1
    google-cloud-datastore: 1.0.0

Following the instructions: https://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html, as it states following the instructions should "just work", but it doesn't because it 
creates an `authorized_user` credential in `$HOME/.config/gcloud/application_default_credentials.json`, which has no `project_id`.

    from google.cloud import datastore
    client = datastore.Client()

Fails with: `OSError: Project was not passed and could not be determined from the environment.` A simple workaround is to pass the `project` in as arg or set an environment variable.

According to `google.auth._default.py`:

     if credential_type == _AUTHORIZED_USER_TYPE:
        ...
        return credentials, None

This is used by [`google.cloud._helpers.py`](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/core/google/cloud/_helpers.py) in `_determine_default_project()`.

Note: `configurations/config_default` does have:

     [core]
     project = <project_id>
     account = <account_id>

**Comment by jonparrott** [comment]
@achampion interesting - the project ID should be ascertained from the cloud sdk. Is `gcloud` on your path? Can you give me the output of both `gcloud info` and `gcloud config config-helper --format json` (with any personal info elided, please)?

In the meantime, I'd recommend that you either explicitly provide the project ID or use service account credentials.

**Comment by achampion** [comment]
Sure, `gcloud` is on my path
 
    [0]$ gcloud info
    Google Cloud SDK [156.0.0]

    Platform: [Mac OS X, x86_64] ('Darwin', 'XXX', '16.6.0', 'Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64', 'x86_64', 'i386')
    Python Version: [2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]]
    Python Location: [/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python]
    Site Packages: [Disabled]

    Installation Root: [/Users/XXX/local/google-cloud-sdk]
    Installed Components:
      gsutil: [4.26]
      core: [2017.05.19]
      beta: [2017.03.24]
      gcloud: []
      bq: [2.0.24]
    System PATH: [/Users/XXX/local/google-cloud-sdk/bin:/Users/XXX/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/R.framework/Resources/bin:/opt/local/bin:/usr/local/bin:/opt/local/libexec/gnubin:/usr/bin:/usr/texbin:/bin:/opt/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/usr/bin/X11:.:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home]
    Python PATH: [/Users/XXX/local/google-cloud-sdk/lib/third_party:/Users/XXX/local/google-cloud-sdk/lib:/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload]
    Cloud SDK on PATH: [True]
    Kubectl on PATH: [False]

    Installation Properties: [/Users/XXX/local/google-cloud-sdk/properties]
    User Config Directory: [/Users/XXX/.config/gcloud]
    Active Configuration Name: [default]
    Active Configuration Path: [/Users/XXX/.config/gcloud/configurations/config_default]

    Account: [XXX]
    Project: [XXX]

    Current Properties:
      [core]
        project: [XXX]
        account: [XXX]
        disable_usage_reporting: [True]
      [compute]
        region: [us-central1]
        zone: [us-central1-a]

    Logs Directory: [/Users/XXX/.config/gcloud/logs]
    Last Log File: [/Users/XXX/.config/gcloud/logs/2017.05.30/01.11.17.190235.log]

-----

    [0]$ gcloud config config-helper --format json
    {
      "configuration": {
        "active_configuration": "default",
        "properties": {
          "compute": {
            "region": "us-central1",
            "zone": "us-central1-a"
          },
          "core": {
            "account": "XXX",
            "disable_usage_reporting": "True",
            "project": "XXX"
          }
        }
      },
      "credential": {
        "access_token": "XXX",
        "token_expiry": "2017-05-30T19:19:18Z"
      },
      "sentinels": {
        "config_sentinel": "/Users/XXX/.config/gcloud/config_sentinel"
      }
    }

**Comment by jonparrott** [comment]
Hmm all that seems fine, can you run the following Python and let me know what it spits out?

```python
import google.auth
print(google.auth.default())
from google.auth import _cloud_sdk
print(_cloud_sdk.get_project_id())
```

**Comment by achampion** [comment]
(<google.oauth2.credentials.Credentials object at 0x10ade4240>, None)
    None

**Comment by jonparrott** [comment]
No, it's not due to that. `_get_cloud_sdk_credentials` handles the case after calling `_get_credentials_from_file`:

```python
    if not project_id:
        project_id = _cloud_sdk.get_project_id()
```

A few more things to do to help me figure out where the disconnect is happening. Can you tell me what happens when you run:

```python
import subprocess
from google.auth import _cloud_sdk
print(subprocess.check_out(_cloud_sdk._CLOUD_SDK_CONFIG_COMMAND))
```

**Comment by achampion** [comment]
*humbled* - `gcloud` wasn't on the path for my `jupyter` session, it was started before I downloaded `google-cloud-sdk`.  So TIL you need `gcloud` on the path for the python session.

**Comment by jonparrott** [comment]
@achampion no worries, just happy we figured it out!

This is one of many, many reasons we're going to be strongly recommending service accounts in the future.

**Comment by dhermes** [comment]
> we're going to be strongly recommending service accounts in the future

I have been `<strong>`-y recommending them for more than 2 years :grinning:
