### ISSUE TITLE
Verify OAuth2 Token - Timeout

### ISSUE THREAD

**Issue by DSpeckhals** [GoogleCloudPlatform/google-auth-library-python#170]
It doesn't seem to be possible to specify a timeout when calling `google.oauth2.id_token.verify_oauth2_token`. Because, as I understand it, if no timeout parameter is given when making a request with `requests`, the timeout is infinite, and the thread or process would hang forever.

Would there be any problem with being able to provide an optional `timeout` parameter in `verify_oauth2_token`, or perhaps the other facades around HTTP requests in this library? Or do you think that a timeout parameter could somehow be set when constructing the `transport.requests.Request` object, then used for any subsequent HTTP request?

I would be happy to help if this seems like the way forward.

**Comment by jonparrott** [comment]
I'd be open to adding a `timeout` parameter to the constructor for `google.auth.transport.requests.Request`.

**Comment by vchudnov-g** [comment]
Makes sense. The new `timeout` parameter should probably also have a default value if not specified.

**Comment by jonparrott** [comment]
Empty default (deferring to requests default) seems fine.

**Comment by DSpeckhals** [comment]
Closing because of the suggest in #171.
