### ISSUE TITLE
GCE metadata ping taking ~75 seconds, not timing out after 3 seconds

### ISSUE THREAD

**Issue by davidfontenot** [GoogleCloudPlatform/google-auth-library-python#173]
google-api-python-client: 1.6.2
python version: 3.5.2

```
from google.auth.compute_engine import _metadata
import google.auth.transport._http_client
request = google.auth.transport._http_client.Request()
_metadata.ping(request=request)
```

When running the following script, the default timeout of 3 seconds is not used. I'm instead seeing the script complete in about 75 seconds. If I print out the value of line 4, I get `False`. I'm not sure if that indicates that the call was successful, or if a timeout had occurred. I see this take ~75 seconds consistently If I set the environment variable `GCE_METADATA_TIMEOUT` to a value such as 10, the script still takes ~75 seconds.

I'm running into this issue when using the pandas-gbq library. I'm writing a script to authorize pandas to access the gbq project. That library checks for the default google credentials, which do not exist in my case. [Here's my related issue with that library](https://github.com/pydata/pandas-gbq/issues/73).

Is this an issue with the google-auth library?

**Comment by dhermes** [comment]
@davidfontenot What platform are you using? (I've seen this before on an old desktop running Ubuntu, but it was very hard to reproduce.)

**Comment by davidfontenot** [comment]
@dhermes this is running in an alpine v3.4 Docker container

**Comment by jonparrott** [comment]
I can definitely reproduce this on mac. It's taking way longer than it should. investigating.
