### ISSUE TITLE
Public Certificate Caching During Token Verification

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-auth-library-python#178]
Token verification methods like `verify_token()` and `verify_firebase_token()` doesn't seem to be caching public certs. Is that correct?  Do they make an HTTP request (in `_fetch_certs()`) on each invocation?

This is not necessarily a problem with the above methods, but with the default HTTP transport implementations provided in the library (the `requests` transport for example).

**Comment by dhermes** [comment]
IIRC `oauth2client` **does** have a cache, but we intentionally didn't add one for `google-auth` **at the outset**.

**Comment by jonparrott** [comment]
Closing in favor of #218
