### ISSUE TITLE
The google-auth-httplib2 installation command is syntax error.

### ISSUE THREAD

**Issue by thala321** [GoogleCloudPlatform/google-auth-library-python#208]
From this page https://pypi.python.org/pypi/google-auth-httplib2 the installation command is syntax error.
$ pip install google-auth-httlib2
But it should be:
$ pip install google-auth-httplib2

**Comment by jonparrott** [comment]
This is fixed here: https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/blob/master/README.rst

We just haven't updated the pypi page because we haven't made a release since.
