### ISSUE TITLE
Do NOT include pyc files in the pypi packages

### ISSUE THREAD

**Issue by douardda** [GoogleCloudPlatform/google-auth-library-python#214]
The current version of google-auth (1.2.0) on pypi includes many pyc files as well as a __pycache__ directory; these should not be there.

Thank you for reuploading a clean package on pypi.

**Comment by dhermes** [comment]
In the `sdist` or in the `wheel`?

**Comment by douardda** [comment]
in the sdist: 
```
david@host:~/tmp$ pypi-download  google-auth
OK: google-auth-1.2.0.tar.gz
david@host:~/tmp$ tar vtf google-auth-1.2.0.tar.gz | egrep "\.pyc$"  |wc -l
110
```

**Comment by jonparrott** [comment]
@douardda is this actively causing issues for you or just a minor annoyance? (trying to gauge the severity here).

**Comment by douardda** [comment]
it's an actual issue: I was making a debian package (for which I use pypi as orig source by default), which I cannot do for this package because of these .pyc files: dh_python complains.

Using the tgz from github made my day, but I really prefer to use the same source as a "pip install" does for python packages. And nobody would accept a src archive full of .o, .la or .so files! Why would it be different here?

It would even be better if pypi warned / refused these uploads, but hey.

**Comment by jonparrott** [comment]
Alright, `1.2.1` is on PyPI and should be good.

**Comment by douardda** [comment]
Perfect, thanks!
