### ISSUE TITLE
Spurious log message about projects for ADC of type authorized_user

### ISSUE THREAD

**Issue by craigcitro** [GoogleCloudPlatform/google-auth-library-python#221]
Currently, if I happen to have `GOOGLE_APPLICATION_CREDENTIALS` pointing to a file with user creds, loading those credentials will (rightly!) [fail to determine an associated project](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/757844996c88a127f63fe936fe14c322a7dbd47f/google/auth/_default.py#L93).

However, we then get a log message suggesting that we should [set an environment variable that's never checked in this case](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/757844996c88a127f63fe936fe14c322a7dbd47f/google/auth/_default.py#L150). This can be [annoying for users](https://stackoverflow.com/questions/47423772/how-to-set-project-id-to-avoid-warnings).

Checking `os.environ[environment_vars.PROJECT]` is a one-liner, and seems like it'd fit with the intention in that code. I'm happy to send a PR if that's 👍.

**Comment by jonparrott** [comment]
Send over a PR. :)

> Currently, if I happen to have GOOGLE_APPLICATION_CREDENTIALS pointing to a file with user creds, loading those credentials will (rightly!) fail to determine an associated project.

I'm honestly surprised that works at all.
