### ISSUE TITLE
Outdated example "Hello Analytics Reporting API v4; Python quickstart for service accounts" 

### ISSUE THREAD

**Issue by jaap3** [GoogleCloudPlatform/google-auth-library-python#223]
The Python quickstart quide for the Analytics Reporting API v4 located https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py is outdated.

It uses the deprecated `oauth2client` and imports the legacy `apiclient` instead of `googleapiclient`.

Furthermore in the `print_response` function `print` is used as a statement instead of a function, which is not compatible with python 3.

**Comment by jonparrott** [comment]
Thanks for reporting, I've moved this to our internal issue tracker. Hopefully will be resolved soon.

In the meantime, you should be able to modify [this sample](https://developers.google.com/api-client-library/python/auth/installed-app#example) to use the Analytics Reporting API.
