### ISSUE TITLE
Getting gcloud auth login to work for python

### ISSUE THREAD

**Issue by msj121** [GoogleCloudPlatform/google-auth-library-python#232]
I described the issue on https://stackoverflow.com/questions/48088841/gcloud-auth-login-saves-to-legacy-credentials-folder

I am running the following code from python library:
```
def get_gcloud_oauth2_creds():
  gcfp = '~/.config/gcloud/credentials'
  credfn = os.path.expanduser(gcfp)
  if not os.path.exists(credfn):
    msg = "[edx2bigquery] Authentication error!  You have specified USE_GCLOUD_AUTH in the configuration, but do not have gcloud authentication available.\n"
    msg += "               Please authenticate using 'gcloud auth login' before running this."
    print msg
    raise Exception(msg)
  gcloud_cred = json.loads(open(credfn).read())['data'][0]['credential']
  credentials = Credentials.new_from_json(json.dumps(gcloud_cred))
  return credentials
```

I always hit the error since my `gcloud auth login` is creating its files in `~/.config/gcloud/legacy_credentials`, which does not seem to work for me. Any ideas how to use the legacy_credentials or preferably get gcloud auth login to work?

**Comment by jonparrott** [comment]
Hi @msj121, this library is for allowing applications to authenticate to Google and Google Cloud services. It is unrelated to the Cloud SDK's auth (except through a legacy mechanism).

I suggest that you use service accounts for your application, see https://cloud.google.com/docs/authentication/getting-started

**Comment by msj121** [comment]
@jonparrott I apologize, I did know that, in that case is there a script that can use the legacy credentials folder?

**Comment by msj121** [comment]
@jonparrott Thanks that link finally got me to the exact link I was looking for. I have been searching/working on this for a week with different python approaches and different key files, but that document contained the link to the right json file. So I tried a different approach to connecting with it instead and now it works.

**Comment by jonparrott** [comment]
Good deal!

**Comment by jonparrott** [comment]
Good deal!
