### ISSUE TITLE
DefaultCredentialsError if project in env but not credentials

### ISSUE THREAD

**Issue by maxim-lian** [GoogleCloudPlatform/google-auth-library-python#242]
We use a custom method to get credentials (we need to pass them in through env variables). I think that the library prevents us from using the `GOOGLE_CLOUD_PROJECT` env var - is that right?

Specifically: when initializing a client, the library attempts to find a default project (`> /usr/local/lib/python2.7/dist-packages/google/cloud/_helpers.py(179)_determine_default_project()`), and calls `google.auth.default()`. 

That function only uses `explicit_project_id` if it can find credentials:

```python
    258     from google.auth.credentials import with_scopes_if_required
    259
    260     explicit_project_id = os.environ.get(
    261         environment_vars.PROJECT,
    262         os.environ.get(environment_vars.LEGACY_PROJECT))
    263
    264     checkers = (
    265         _get_explicit_environ_credentials,
    266         _get_gcloud_sdk_credentials,
    267         _get_gae_credentials,
    268         lambda: _get_gce_credentials(request))
    269
    270     for checker in checkers:
    271         credentials, project_id = checker()
# credentials are always none if there are no credentials in environment...
    272         if credentials is not None:
    273             credentials = with_scopes_if_required(credentials, scopes)
# ...so this line is never reached, and explicit_project_id isn't used
    274             effective_project_id = explicit_project_id or project_id
    275             if not effective_project_id:
    276                 _LOGGER.warning(
    277                     'No project ID could be determined. Consider running '
    278                     '`gcloud config set project` or setting the %s '
    279                     'environment variable',
    280                     environment_vars.PROJECT)
    281             return credentials, effective_project_id
    282
--> 283     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
```

Is this intended? We can pull `GOOGLE_CLOUD_PROJECT` manually and pass that in, though the auto-fallback to the env var is a bit of convenience

**Comment by jonparrott** [comment]
How are you constructing your client? You can always just pass the project ID into the client constructor explicitly.

**Comment by maxim-lian** [comment]
Constructing the client with 

```python
bigquery.Client(project=project, credentials=get_credentials())

def get_credentials():
    """
    Pull credentials, for use in BigQuery library
    """
    if os.getenv('GCLOUD_KEY_B64'):
        key = standard_b64decode(os.getenv('GCLOUD_KEY_B64'))
        return service_account.Credentials.from_service_account_info(
            json.loads(key))
    try:
        GoogleCredentials.get_application_default()
    except:
        raise AttributeError("""
            If running interactively, first run `dc run --rm gcloud-auth` to
            create application default creds needed for bigquery.
            For production, the env var GCLOUD_CREDS_B64 should contain the
            base64'd contents of a service account json file.
            Example: `export GCLOUD_KEY_B64="$(base64 gbq-creds.json)"`
        """)
```

...and, I agree, we could do something like this, moving that check upstream:

```python
bigquery.Client(project=project or os.getenv('GOOGLE_CLOUD_PROJECT'), credentials=get_credentials())
```

**Comment by jonparrott** [comment]
Cool. I'm going to go ahead and close this.

**Comment by maxim-lian** [comment]
OK that's reasonable.

An aside - is there any reasonable way of passing creds using environment variables? In our CI, we're not running on Google machines, so we do this dance to try and pass them in with env vars.

Is there a better way?

Thanks

**Comment by jonparrott** [comment]
@maxim-lian I'm not sure what you mean, but you can always specify credentials using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable which should point to a service account json file.

**Comment by maxim-lian** [comment]
> specify credentials using the GOOGLE_APPLICATION_CREDENTIALS environment variable which should point to a service account json file.

Right, though we still need to map a file into the container - we can't put the actual credential in an env var

**Comment by jonparrott** [comment]
Correct, this is entirely intentional. See https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/

**Comment by maxim-lian** [comment]
Thank you!
