### ISSUE TITLE
google Sheets API docs use oauth2client

### ISSUE THREAD

**Issue by bergey** [GoogleCloudPlatform/google-auth-library-python#247]
https://developers.google.com/sheets/api/quickstart/python

only shows use of `oauth2client`, not `google.auth`.  [google-auth docs](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html) suggest this is the correct place to report this.

**Comment by theacodes** [comment]
@grant can you take a look at this?

**Comment by grant** [comment]
Hi Daniel,
Can you please file the issue here?:
https://github.com/gsuitedevs/python-samples

That developers.google.com page links the code to the `quickstart.py` GitHub file source too.

**Comment by slokhorst** [comment]
For reference: gsuitedevs/python-samples#10

And the quickstart.py file: https://github.com/gsuitedevs/python-samples/blob/master/drive/quickstart/quickstart.py

**Comment by grant** [comment]
@theacodes You can close this bug in favor of the python-samples bug.

**Comment by theacodes** [comment]
Thanks, @grant!
