### ISSUE TITLE
Credentials property for NDB from oauth2client unsupported

### ISSUE THREAD

**Issue by christophe-riolo** [GoogleCloudPlatform/google-auth-library-python#248]
Hello,
Im my project I am making use of those features from oauth2client:
https://developers.google.com/api-client-library/python/guide/google_app_engine#credentials
https://developers.google.com/api-client-library/python/guide/google_app_engine#storage

Alas, upon reporting a bug I saw that the library was deprecated, but I did not find an equivalent here.

I will also at the same time report said bug here in case you will be porting the code.
When the credentials are stored in an entity that has a `parent`, you need to specify the parent to be able to retrieve the entity (see https://cloud.google.com/appengine/docs/standard/python/ndb/modelclass#class_methods method `get_by_id`). It is however impossible to specify the parent when using StorageByKeyName so the credentials are impossible to retrieve from entities that have a parent.

Thank you for the very clear and useful library.

Christophe

**Comment by jonparrott** [comment]
The discussion around Storage in this library is covered here: https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/33

As for your other question, it might be better to ask on Stackoverflow.

(Closing for now, happy to keep discussing)
