### ISSUE TITLE
credentials could not be converted to unicode

### ISSUE THREAD

**Issue by arun542** [GoogleCloudPlatform/google-auth-library-python#253]
I get my authentication credentials using google.oauth2.credentials, google_auth_oauthlib.flow libraries, then store in my database. when i try to load credentials from database (dictionary) and create object using google.oauth2.credentials.Credentials, them try to run:

service = googleapiclient.discovery.build('calendar', 'v3', credentials = credentials)

it gives me this error:
{0!r} could not be converted to unicode'.format(value)

I am using python 2.7 and postgress + sqlalchemy database

**Comment by mearajennifer** [comment]
Hi, I'm having the same error (but for the Calendar API) with python3.6, flask, postgresql, and sqlalchemy. How did you solve this?

**Comment by Sevenanths** [comment]
If anyone else were to have this issue: load your credentials from wherever you get them and feed them to google.oauth2.credentials.Credentials as follows:

```
credentials_dict = json.loads(content)

credentials = google.oauth2.credentials.Credentials(
    credentials_dict["token"],
    refresh_token = credentials_dict["refresh_token"],
    token_uri = credentials_dict["token_uri"],
    client_id = credentials_dict["client_id"],
    client_secret = credentials_dict["client_secret"],
    scopes = credentials_dict["scopes"])
```

The trick is to feed the values as individual arguments, not as a dict.

**Comment by 808sAndBR** [comment]
It will also worked for me by instead read the json in as a string instead of reading it in as actual json.

ex:
```
with open('auth.json') as f:
    auth = f.readline()

gc = gspread.authorize(GoogleCredentials.from_json(auth))
```

**Comment by Hikaon** [comment]
> If anyone else were to have this issue: load your credentials from wherever you get them and feed them to google.oauth2.credentials.Credentials as follows:
> 
> ```
> credentials_dict = json.loads(content)
> 
> credentials = google.oauth2.credentials.Credentials(
>     credentials_dict["token"],
>     refresh_token = credentials_dict["refresh_token"],
>     token_uri = credentials_dict["token_uri"],
>     client_id = credentials_dict["client_id"],
>     client_secret = credentials_dict["client_secret"],
>     scopes = credentials_dict["scopes"])
> ```
> 
> The trick is to feed the values as individual arguments, not as a dict.

Shorter version:
`credentials = google.oauth2.credentials.Credentials(**credentials_dict)`
