### ISSUE TITLE
Broken LICENSE, CONTRIBUTING links in docs

### ISSUE THREAD

**Issue by salty-horse** [GoogleCloudPlatform/google-auth-library-python#259]
The bottom of `google-auth-library-python/docs/index.rst` links to `LICENSE` and `CONTRIBUTING.rst` on GitHub with broken URLs:
`https://github.com/GoogleCloudPlatform/google-auth-library-python/LICENSE`
`https://github.com/GoogleCloudPlatform/google-auth-library-python/CONTRIBUTING.rst`

**Comment by theacodes** [comment]
Thanks, @salty-horse!
