### ISSUE TITLE
Use PEP420 valid tags

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-auth-library-python#26]
If you want RTD to build a `stable` version of docs on a tag, the tag needs to be PEP420 valid, so `v0.0.1` is a no-go.

From their [documentation][1], a `stable` build is only done when a semver-valid tag is pushed:

> You should push a tag for each version of your project. These tags should be numbered in a way that is consistent with [semantic versioning][2]. This will map to your stable branch by default.

[1]: http://docs.readthedocs.io/en/latest/versions.html
[2]: http://semver.org/

**Comment by jonparrott** [comment]
@dhermes is the issue the presence of `v` in the tag?

**Comment by dhermes** [comment]
It seems I'm wrong?

```python
>>> from packaging.version import Version
>>> Version('v0.0.1')
<Version('0.0.1')>
```

**Comment by jonparrott** [comment]
Yeah the `v` is PEP420 compliant, but not semver.

**Comment by jonparrott** [comment]
It seems rtd is building stable with the v0.0.1 tag. Is there anything to do here? http://google-auth.readthedocs.io/en/stable/

**Comment by dhermes** [comment]
Nope
