### ISSUE TITLE
Doesn't work when used with kubernetes package

### ISSUE THREAD

**Issue by wvxvw** [GoogleCloudPlatform/google-auth-library-python#269]
The real issue is that you decided to outsmart yourselves by putting this little "beauty" into `google_auth-1.5.0-py3.6-nspkg.pth`:

(formatted for somewhat improved readability)

```
import sys, types, os
has_mfs = sys.version_info > (3, 5)
p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',))
importlib = has_mfs and __import__('importlib.util')
has_mfs and __import__('importlib.machinery')
m = has_mfs and sys.modules.setdefault('google', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('google', [os.path.dirname(p)])))
m = m or sys.modules.setdefault('google', types.ModuleType('google'))
mp = (m or []) and m.__dict__.setdefault('__path__',[])
(p not in mp) and mp.append(p)
```

Why on Earth would you do this?  This is so unnecessary... so fragile, and so wrong on so many levels... and, of course, doesn't work in the end.

Please, just don't do this.  Whatever your reasons were for doing this: it is not worth it.  Please, don't try to fix the code above to work in this specific case of Kubernetes client, just delete it.

In case you are interested to see what the error looks like:

```
../../../.local/share/virtualenvs/tests-H2T6kjqq/lib/python3.6/site-packages/kubernetes/__init__.py:20: in <module>
    import kubernetes.config
../../../.local/share/virtualenvs/tests-H2T6kjqq/lib/python3.6/site-packages/kubernetes/config/__init__.py:17: in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
../../../.local/share/virtualenvs/tests-H2T6kjqq/lib/python3.6/site-packages/kubernetes/config/kube_config.py:22: in <module>
    import google.auth
E   ModuleNotFoundError: No module named 'google.auth'
```

**Comment by tseaver** [comment]
Note that *we* (the project in this repository) don't manage the contents of any `*-nspkg.pth` files:  those files are generated by `pip` / `setuptools` when installing wheels which declare namespace packages.

Please try updating both `pip` and `setuptools` in a fresh virtual environment before installing `google-auth`, e.g.:

```bash
$ /path/to/python-x.y/bin/python -m venv /tmp/ga-269
$ /tmp/ga-269/bin/pip install --upgrade setuptools pip
...
Successfully installed pip-10.0.1 setuptools-39.2.0
$ /tmp/ga-269/bin/pip install google-auth
...
Successfully installed cachetools-2.1.0 google-auth-1.5.0 pyasn1-0.4.3 pyasn1-modules-0.2.1 rsa-3.4.2 six-1.11.0
$ /tmp/ga-269/bin/python -c "import google.auth"
```

**Comment by dkasyanov** [comment]
Hi @theacodes!

That's very cool that namespace_packages work within googleapis and google-cloud-platform but we also have GoogleAppEngineSDK. It is also provides google namespace, but there are no `declare_namespace` workaround in it

As said in https://packaging.python.org/guides/packaging-namespace-packages/
```__import__('pkg_resources').declare_namespace(__name__)``` should be in all packages that are using same namespace (***google*** in our case).

Is there any normal workaround for this?
I really dislike the approach with importing google and modifying `google.__path__`
I use both NDB and google-api-python-client in same project and cannot run tests via the IDE (PyCharm).
Some solution - https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting?csw=1#setup
But it allows to run tests from CLI without IDE.

**Comment by theacodes** [comment]
@dkasyanov please file a separate issue.
