### ISSUE TITLE
Can't make this work: Please confirm I'm doing it right.

### ISSUE THREAD

**Issue by tobiasbp** [GoogleCloudPlatform/google-auth-library-python#272]
Hello...

I'm having problems making this library work. Is there a more appropriate place to ask questions than here? I have not been able to find any references to a forum or a list.

I'm looking at the documentation here: https://google-auth.readthedocs.io/en/latest/user-guide.html

I have created a service account, downloaded the private key, enabled API's and given the service account access to my G Suite domain to scope ('https://www.googleapis.com/auth/admin.directory.user').

Based on the documentation, I have this simple code:
 
```
import google.auth
from google.auth.transport.requests import AuthorizedSession

# Set this ENV variable
# $ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/key.json

credentials, project = google.auth.default(scopes=['https://www.googleapis.com/auth/admin.directory.user'])

authed_session = AuthorizedSession(credentials)

response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users')

```
I'm expecting a list of users in the domain, but get a '400: Bad request'

If I try to get info on a user like this:
`response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users/foo@example.com')`

I get a '403: Not Authorized to access this resource/api'

Any suggestions much appreciated.

Also, I don't understand, if the following quote means I need to install relevant libraries to use the approach above (I get no errors, so I don't think so)?:

> When running on any Google Cloud hosting environment or when running locally with the Google Cloud SDK installed, default() can automatically determine the credentials from the environment

When trying this approach from the documentation:
```
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/path/to/key.json')

scoped_credentials = credentials.with_scopes(
    ['https://www.googleapis.com/auth/cloud-platform'])
```

I get the following error:
`google.auth.exceptions.RefreshError: ('invalid_scope: Empty or missing scope not allowed.', u'{\n  "error" : "invalid_scope",\n  "error_description" : "Empty or missing scope not allowed."\n}')
`

Thank you,
Tobias

**Comment by theacodes** [comment]
Your first attempt is mostly right, however, you have to *delegate* the credentials to a domain administrator in order to access the G Suite admin APIs, for example:

```python

credentials, project = google.auth.default(scopes=['https://www.googleapis.com/auth/admin.directory.user'])

admin_credentials = credentials.with_subject('admin@example.com')

authed_session = AuthorizedSession(credentials)

response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users')
```

see [here](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#domain-wide-delegation) for more details.

**Comment by tobiasbp** [comment]
Hello @theacodes 

Thank you for helping me out here.

I'm trying out you suggestions. I can only make it (partially) work when using the admin credentials on the session like this:
`authed_session = AuthorizedSession(admin_credentials)` 

If I create the session like you suggest:
`authed_session = AuthorizedSession(credentials)`

I get the message:

> Not Authorized to access this resource/api

When using the admin credentials on the session, I still can not get a list of users in the domain with this line:
`response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users')`

I get the error:
> Bad Request

I can however (Using the admin credentials) get info in a user with this line:
`response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users/foo@example.com')
`

Any suggestions much appreciated.

Thank you,
Tobias

**Comment by tobiasbp** [comment]
I realized, that I obviously need to say which domain I want to list users for. It's done like this:
`response = authed_session.get('https://www.googleapis.com/admin/directory/v1/users?domain=example.com')
`

**Comment by theacodes** [comment]
@tobiasbp did you get it working?

**Comment by tobiasbp** [comment]
@theacodes Yes I did. Thank you for helping me out. However, I can't update my users as described in #273.
