### ISSUE TITLE
How to send body using PUT?

### ISSUE THREAD

**Issue by tobiasbp** [GoogleCloudPlatform/google-auth-library-python#273]
I'm attempting to update a G Suite user with the data in the following dictionary:
```
{
    "organizations": [
        {
            "customType": "",
            "location": "Tokyo, Japan",
            "name": "Example Inc.",
            "primary": true,
            "title": "FUD evangalist",
            "type": "work"
        }
    ]
}
```
This is the URL I'm using:
`URL = 'https://www.googleapis.com/admin/directory/v1/users/user@example.com'`

Looking at the [documentation](http://google-auth.readthedocs.io/en/latest/reference/google.auth.transport.requests.html), it looks to me like I should be able to PUT the dictionary directly like this:
`response = authed_session.put(URL, data = dictionary_to_send)`

This gives me the error:
> This API does not support parsing form-encoded input.

The I try to send the dictionary as JSON:
`response = authed_session.put(URL, data = json.dumps(dictionary_to_send))`

This gives me the users data back, as expected. But, the user has not been updated with the data in the dictionary.

I have pasted the dictionary as a JSON in to the API Explorer. The changes are applied when I do that.

Any suggestions?

**Comment by theacodes** [comment]
Hey @tobiasbp! This question might be better asked on StackOverflow. Perhaps @grant can help out here?

**Comment by grant** [comment]
I don't know the issue off-hand.
Given you've successfully called the API in the API Explorer, it seems like a python client issue rather than an API issue.

**Comment by theacodes** [comment]
@grant  Considering they're not using a client library but making the request using Requests, I doubt there's an issue with the client library at play. It seems that the API expect a specific encoding for the request, can you help us get to the bottom of that?

**Comment by theacodes** [comment]
You can use [session.prepare_request](http://docs.python-requests.org/en/master/api/#requests.Session.prepare_request) and print that out to see exactly what's sent.

**Comment by tobiasbp** [comment]
hello @theacodes 

I have done as you suggested (I think):

```
URL = 'https://www.googleapis.com/admin/directory/v1/users/foo@example.com'
request = requests.Request(method = 'PUT', url = URL, json = json.dumps(data_to_send))
prepared_request = authed_session.prepare_request(request)
response = authed_session.send(prepared_request)

```
URL:

> https://www.googleapis.com/admin/directory/v1/users/foo@example.com

Headers:

> {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/json', 'Content-Length': '198', 'Connection': 'keep-alive', 'User-Agent': 'python-requests/2.9.1'}

Body:
> "{\"organizations\": [{\"customType\": \"\", \"primary\": true, \"name\": \"example company\", \"title\": \"Some position\", \"location\": \"Japan\", \"type\": \"work\"}]}"

Response:
> {'error': {'errors': [{'location': 'Authorization', 'message': 'Login Required', 'locationType': 'header', 'domain': 'global', 'reason': 'required'}], 'message': 'Login Required', 'code': 401}}

I can read data using the same session, so I don't see how it could not have authorization? The user has access to this scope:
> https://www.googleapis.com/auth/admin.directory.user

So, I have learned, that I should probably use json = XX instead of data = XX when sending data.This is, of course very reasonable :)

So, now that I'm wiser, I'll change my original PUT (json = x, not data = x)  to:
`response = authed_session.put(URL, json = json.dumps(data_to_send))
`
This is returns the user's unchanged info as a JSON.

This behavior makes no sense to me?? Now, I am authorized, but the changes are not applied?

**Comment by theacodes** [comment]
@tobiasbp service account credentials will be invalid until they're refreshed for the first time. Your first request should do that, so *after* your request you should see a valid token.

@grant can you take a look at this? I don't have access to a gsuite domain to test with.

**Comment by grant** [comment]
I successfully tested the endpoint with an admin account using the explorer here:
https://developers.google.com/admin-sdk/directory/v1/reference/users/update

![screen shot 2018-06-22 at 12 23 13](https://user-images.githubusercontent.com/744973/41795325-2abb6a24-7617-11e8-86d0-1aac475f1eac.png)
![screen shot 2018-06-22 at 12 23 29](https://user-images.githubusercontent.com/744973/41795326-2ad2153a-7617-11e8-8b9f-66c6b1e68f87.png)

I really thing this is a user error with authorizing the client rather than the Admin SDK Directory API. We should at least get a 403 rather than a 401. Given the title of the issue and the current authorization errors @tobiasbp is seeing, I honestly don't see where the API service is having the issue.

**Comment by theacodes** [comment]
@grant it might be useful to try out their provided code to see if you can get it working? Happy to help - feel free to ping me on chat.

**Comment by grant** [comment]
Pinged on chat.

**Comment by tobiasbp** [comment]
Just for the record: I'm not suggesting anything is broken, I'm just asking
for help on how to use the library.

**Comment by tobiasbp** [comment]
@theacodes Does it make sense, that I can read user data from my G Suite domain with an invalid token?

**Comment by tobiasbp** [comment]
I finally found out what was wrong.

Wrong:
`response = authed_session.put(URL, json = json.dumps(data_to_send))
`

Right:
`response = authed_session.put(URL, json = data_to_send)`

data_to_send is a python dictionary. Some APIs will tell you the wrong way is indeed wrong, other will not.

**Comment by tobiasbp** [comment]
What is the task here ? @JustinBeckwith
