### ISSUE TITLE
Consider removing namespace_packages argument from setup.py

### ISSUE THREAD

**Issue by calder** [GoogleCloudPlatform/google-auth-library-python#274]
The `namespace_packages` argument to `setup` prevents `google/__init__.py` from being included in the Pip package, which in turn prevents Bazel [rules_python](https://github.com/bazelbuild/rules_python) from treating `google` as a namespace package. This makes it incompatible with the protobuf package (and any other google-rooted packages) when used under Bazel.

https://github.com/bazelbuild/rules_python/issues/93 tracks adding support for namespace_packages in rules_python.

**Comment by theacodes** [comment]
Sorry, we can't do that. There are roughly 40 packages that live under the google namespace. All of them must cooperate for this to work. Bazel needs to be fixed to support namespace packages.
