### ISSUE TITLE
Support standard GAE Python3

### ISSUE THREAD

**Issue by fili** [GoogleCloudPlatform/google-auth-library-python#291]
The new standard GAE Python3 is [not supporting App Identity](https://cloud.google.com/appengine/docs/standard/python3/python-differences#app_engine_apis). As such, [this](https://google-auth.readthedocs.io/en/latest/reference/google.auth.app_engine.html#module-google.auth.app_engine) does not work on the new standard GAE Python3.

**Comment by theacodes** [comment]
We already do. Python3 on GAE standard provides the GCE metadata service, so GCE credentials work.

**Comment by tseaver** [comment]
@theacodes the question was about `google.auth.appengine.Signer`.

@fili You can use the "normal" signers, e.g.:

```python
from google.auth import crypt

with open('private_key.pem') as key_file:
    private_key = key_file.read()

signer = crypt.RSASigner.from_string(private_key)
signature = signer.sign(message)
```
