### ISSUE TITLE
provide a way to suppress service warning

### ISSUE THREAD

**Issue by kapilt** [GoogleCloudPlatform/google-auth-library-python#292]
for cli apps that users are expected to run it would be nice if we could suppress the warning thats this library generates. afaics this isn't something an application can supress currently without monkeypatching this library.

/Users/kapil/projects/cloud-custodian/lib/python3.6/site-packages/google/auth/_default.py:66: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

**Comment by theacodes** [comment]
This is working as intended. If you are making an application that is receiving this warning, you should do the OAuth 2.0 authorization flow yourself instead of relying on Cloud SDK.
