### ISSUE TITLE
SSL Certificate Error when trying to  connect to DLP API

### ISSUE THREAD

**Issue by RobMohr** [GoogleCloudPlatform/google-auth-library-python#295]
Hello, as the title says i'm receiving an SSL certificate error when trying to hit endpoints in the DLP API. I receive this error when using the requests package or the Client API. Just to note: I can hit the desired endpoints just fine with curl.

The error using Client API looks like:
```
E0920 15:02:05.878961000 140736148943744 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

The error using requests looks like:
```
Traceback (most recent call last):
  File "test_requests.py", line 37, in <module>
    resp = requests.post(call_url, params=payload, headers=api_call_headers, proxies=proxies)
  File "/Users/uname/Desktop/Projects/python-docs-samples/dlp/.venv/lib/python3.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/uname/Desktop/Projects/python-docs-samples/dlp/.venv/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/uname/Desktop/Projects/python-docs-samples/dlp/.venv/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/uname/Desktop/Projects/python-docs-samples/dlp/.venv/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ikj343/Desktop/Projects/python-docs-samples/dlp/.venv/lib/python3.7/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='dlp.googleapis.com', port=443): Max retries exceeded with url: /v2/projects/p-apps-sbx6-delete-on-06102018/content:inspect?item=value&inspectConfig=includeQuote&inspectConfig=minLikelihood&inspectConfig=infoTypes (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

I can set requests to not verify certificates (which isn't ideal), but I see no such workaround with the Python Client API.

I have tried updating the relevant packages:
pip install --upgrade google-api-python-client
pip install --upgrade google-cloud
pip install --upgrade google-cloud-dlp
pip install --upgrade requests
pip install --upgrade certifi
gcloud components update
pip install requests[security]

Python Version: 3.7.0
OpenSSL Version: 1.0.2p

Is there a good way to fix this issue?

**Comment by tseaver** [comment]
@RobMohr What OS version are you using?  I just [tested the `dlp.googleapis.com` certificates using ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=dlp.googleapis.com&latest) and found no issues.

Maybe your Python is using an old / stale cert store?

Please reopen if you can provide more information.
