### ISSUE TITLE
Implement service_account.Credentials.to_jwt_credentials()

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#35]
(Context: #29)

**Comment by anthmgoogle** [comment]
Sorry for the late follow. Allowing easy "promotion" like this is good and what we did in a couple of other languages. One thing about JWT credentials is that they have a much larger request header footprint, and so are better suited to HTTP 2.0 which can cache large headers.

**Comment by jonparrott** [comment]
Good to hear we made the right choice. Thanks!
