### ISSUE TITLE
oauth2client deprecation plan

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#71]
In order to deprecate oauth2client:

1. [x] Add support for google-auth to google-gax.
2. [x] Add support for google-auth to google-cloud-python.
3. [x] Add support for google-auth to google-api-python-client.
1. [x] Release v1.0.0.
4. [x] Figure out a story for obtaining user auth credentials (oauthlib integration?).
5. [ ] Update auth documentation on developers.google.com and cloud.google.com to point to google-auth.

Am I forgetting anything?

**Comment by nathanielmanistaatgoogle** [comment]
Sorry that I've been keeping this rolling around in my mind over the last week rather than bringing it up as I've been meaning to do, but how about a list item to [decide whether `grpcio` depends on `google-auth-library-python` or whether `google-auth-library-python` depends on `grpcio`](https://github.com/grpc/grpc/issues/6799)?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle at present it's that google-auth can provide authentication for gRPC. I strongly think this is the right thing to do. gRPC is a transport and there are many ways to authenticate to a gRPC service. google-auth provides *one* of those ways.

**Comment by jonparrott** [comment]
oauthlib integration seems possible, and even pretty easy, see #74.

**Comment by jonparrott** [comment]
Update on this: google-cloud-python 0.22 has switched from oauth2client to google-auth.

I'm going to add support for *both* in google-api-python-client sometime in January.

**Comment by jonparrott** [comment]
PR for google-auth support in google-api-python-client: https://github.com/google/google-api-python-client/pull/319

**Comment by bjwatson** [comment]
Sorry, the Github UI makes it too easy to clear all assignees when you attempt to add someone who's not yet a collaborator in the repo.

**Comment by jonparrott** [comment]
I've just released [v1.6.0 of google-api-python-client]() which now supports both `oauth2client` and `google-auth` and preferentially uses `google-auth` for Application Default Credentials.

One step closer.

**Comment by jonparrott** [comment]
oauth2client is now deprecated. I'm closing this.

The docs still need to be updated, but there's a lot of inertia there that can not be directly addressed by the maintainers of this project (but it will still be something I'm seeing through).
