### ISSUE TITLE
Consider making `service_account_email` part of the `Signing` interface

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/google-auth-library-python#85]
google-cloud-python needs both a signer and a service account email to identify the signer to make a [signed url](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/115748814bf6a59d99c13e070dfdcfbdec5e865d/core/google/cloud/credentials.py#L119).

/cc @dhermes

**Comment by dhermes** [comment]
:+1: This is a no-brainer?

**Comment by jonparrott** [comment]
Should it be `service_account_email`? Should it just be `signer_email`?

**Comment by dhermes** [comment]
I don't know. You seem to have read the RFC?

**Comment by jonparrott** [comment]
This is pretty removed from the RFC's scope. JWT has the concept of an `issuer`.
